// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using MudBlazorApp.Server.Data.Context;

#nullable disable

namespace MudBlazorApp.Server.Migrations
{
    [DbContext(typeof(SupplierDbContext))]
    [Migration("20230705202746_AddedSupplierTable")]
    partial class AddedSupplierTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("MudBlazorApp.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb33a535-49a9-45a8-898e-18262f130f50"),
                            Company = "GetTech Limited",
                            Email = "gt@limited.com",
                            Name = "ABC"
                        },
                        new
                        {
                            Id = new Guid("a4448693-6afa-4b10-9653-835a522a5ef9"),
                            Company = "Cleaning Limited",
                            Email = "clean@limited.com",
                            Name = "IJK"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
